# -*- coding: utf-8 -*-
#"""Gibson_Villaflor_2399376_Week3_Netflix_Dashboard_Streamlit.ipynb

#Automatically generated by Colab.

#Original file is located at
    #https://colab.research.google.com/drive/1Y9nMhIv_Ij_Aw1bZMjyiv7-RLFGD_XVv
#"""



# Import libraries
import streamlit as st
import pandas as pd
import altair as alt
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

# Page Title
st.set_page_config(
    page_title="Netflix Dashboard",
    page_icon=":movie_camera:",
    layout="wide",
    initial_sidebar_state="expanded")
st.title(':clapper: Netflix Dashboard')
alt.themes.enable("dark")

# Load data
df = pd.read_csv('netflix_titles.csv')

# Sidebar
with st.sidebar:
    st.title('🎦 Netflix Dashboard')
    chart_choice = st.radio(
        'Select a chart',
        ['Movie vs TV Show', 'Release Year Distribution', 'Top 10 Countries', 'Top 10 Categories']
    )

# Visualization — only shows in the dashboard the chart that matches the sidebar selection

if chart_choice == 'Movie vs TV Show':
    col1, col2 = st.columns(2)
    with col1:
        fig1, ax1 = plt.subplots(figsize=(6,5))
        sns.countplot(x='type', data=df, ax=ax1)
        ax1.set_title('Total Number of Movie and TV Show', size=16)
        ax1.set_xlabel('Type', size=12)
        ax1.set_ylabel('Count', size=12)
        st.pyplot(fig1)
        st.dataframe(df.type.value_counts())
    with col2:
        type_counts = df['type'].value_counts()
        fig2, ax2 = plt.subplots(figsize=(6,6))
        ax2.pie(type_counts, labels=type_counts.index, autopct='%1.1f%%', startangle=90)
        ax2.set_title('Movies vs TV Shows', size=16)
        st.pyplot(fig2)
    st.dataframe(df['type'].describe())

elif chart_choice == 'Release Year Distribution':
    fig, ax = plt.subplots(figsize=(10,6))
    sns.histplot(x='release_year', data=df, ax=ax)
    ax.set_title('Distribution of Release Year', size=18)
    ax.set_xlabel('Year', size=14)
    ax.set_ylabel('Count', size=14)
    st.pyplot(fig)
    st.dataframe(df["release_year"].value_counts().head(10))
    st.dataframe(df["release_year"].describe())

elif chart_choice == 'Top 10 Countries':
    fig, ax = plt.subplots(figsize=(10,6))
    df['country'].value_counts().head(10).plot(kind='bar', ax=ax)
    ax.set_title('Top 10 Countries', size=18)
    ax.set_xlabel('Country', size=14)
    ax.set_ylabel('Number of Titles', size=14)
    st.pyplot(fig)
    st.dataframe(df["country"].value_counts().head(10))
    st.dataframe(df["country"].describe())

elif chart_choice == 'Top 10 Categories':
    fig, ax = plt.subplots(figsize=(10,6))
    df['listed_in'].value_counts().head(10).plot(kind='bar', ax=ax)
    ax.set_title('Top 10 Categories', size=18)
    ax.set_xlabel('Listed In', size=14)
    ax.set_ylabel('Counts', size=14)
    st.pyplot(fig)
    st.dataframe(df["listed_in"].value_counts().head(10))
    st.dataframe(df["listed_in"].describe())













